version: '3.8'

services:
  web:
    build: .
    container_name: fun_finder
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tennis_reservation
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google_default_credentials.json
      - ENV=development
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials/google_default_credentials.json

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tennis_reservation
    ports:
      - "5432:5432"